[project]
name = "test-single-port-django-vue"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.3",
    "django-vite>=3.0.5",
    "djangorestframework>=3.15.2",
]
